# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: electronuserland/builder:wine

stages:
  - test
  - dist
  - upload
  - release

variables:
  PACKAGE_VERSION: "0.0.1"
  SETUP_WIN_BINARY: "Electron React App Setup ${PACKAGE_VERSION}.exe"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/electron-react-app/${PACKAGE_VERSION}"



# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - .yarn/

test:electron:
  stage: test
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
  script:
    - npm run test

dist:electron:
  stage: dist
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
  script:
    - npm run electron:build
    - ls -al dist
  artifacts:
    paths:
      - "dist/${SETUP_WIN_BINARY}"

#    - node ./specs/start.js ./specs/async.spec.js

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "dist/${SETUP_WIN_BINARY}" $( echo "${PACKAGE_REGISTRY_URL}/${SETUP_WIN_BINARY}" | sed 's/ /%20/g' )


release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${SETUP_WIN_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${SETUP_WIN_BINARY}\"}" \

